### PR TITLE
Changed null should not override default values.

### PR DESCRIPTION
**Pull request by fabianmarz**
### Description
- When null is passed the default component value should not be overridden

### CODE REVIEW

**Comment by sun** [comment]
This sounds like a weird edge case to me. Do you remember the real world code example that led to this PR?

**Comment by wrux** [comment]
> This sounds like a weird edge case to me. Do you remember the real world code example that led to this PR?

@sun If you try something like this:
```
{% render '@atoms/headings/heading.twig' with {
  text: null,
} %}
```

The heading component has a default value for text (should probably be removed), but if you parse in null it will over-ride the value.

**Comment by fabianmarz** [comment]
@sun, I think we talked about this when passing keys explicitly to see at a glance, what values are supported by the component similar as @wrux wrote. 🤔

**Review by sun — COMMENTED** [review]
I guess we can move forward with this, but this expected behavior should be documented in the readme.

**Review by wrux — APPROVED** [review]

**Pull request merged**
